name: Build

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: never
  NO_COLOR: true
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup Rust and Cargo
        uses: moonrepo/setup-rust@v1.2.2
        with:
          profile: minimal
      - name: Install system dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends libudev-dev libhidapi-dev libpulse-dev
      - name: Restore modification times
        uses: chetan/git-restore-mtime-action@v2
      - name: Build release binary
        run: cargo build --release --locked ${{ matrix.features }}

