name: Cargo Assist

permissions:
  contents: write

on:
  push:

jobs:
  cargo-assist:
    name: Cargo Assist
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Install system dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends libudev-dev libhidapi-dev libpulse-dev
      - name: Run Cargo Assist
        uses: MarcoIeni/cargo-assist@v0.1
        with:
          clippy_allow_dirty: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
