name: upgrade

on:
  workflow_dispatch:

jobs:
  cargo-upgrade:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.94.1
      - name: Cache
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install cargo-edit
        run: cargo install cargo-edit --locked
      - name: Upgrade dependencies
        run: |
          cargo upgrade
          cargo update
      - name: Create pull request
        uses: peter-evans/create-pull-request@v8
        with:
          commit-message: "chore: upgrade dependencies"
          title: "chore: upgrade dependencies"
          body: |
            Automated dependency upgrade generated by the upgrade workflow.
          branch: github-actions/upgrade-dependencies
