name: upgrade

on:
  workflow_dispatch:

env:
  CARGO_EDIT_VERSION: 0.13.9

jobs:
  cargo-upgrade:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.94.1
      - name: Cache
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-edit-${{ env.CARGO_EDIT_VERSION }}
      - name: Install cargo-edit
        run: |
          if ! cargo install --list | grep -q "^cargo-edit v${CARGO_EDIT_VERSION}:"; then
            cargo install cargo-edit --locked --version "${CARGO_EDIT_VERSION}"
          fi
      - name: Upgrade dependencies
        run: |
          cargo upgrade
          cargo update
      - name: Create pull request
        uses: peter-evans/create-pull-request@v8
        with:
          commit-message: "chore: upgrade dependencies"
          title: "chore: upgrade dependencies"
          body: |
            Automated dependency upgrade generated by the upgrade workflow.
          branch: github-actions/upgrade-dependencies
